/**
 * FileUploadController
 *
 * @description :: Server-side logic for uploading files
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */
var multer = require('multer');
module.exports = {
	upload: function(req,res){
		
		var fs = require('fs');
		// string generated by canvas.toDataURL()
		var img = req.body.file;
		// strip off the data: url prefix to get just the base64-encoded bytes
		var data = img.replace(/^data:image\/\w+;base64,/, "");
		var buf = new Buffer(data, 'base64');
		// console.log(buf);
		fs.writeFile('E:/wamp/www/Vcancy/login/dist/images/'+req.body.filename, buf, function (err, data) {
			  if (err) {
				res.json("error");
			  } else {
				res.json("success");
			  }
		});
	}
  
};

